create table words (
    id int primary key auto_increment,
    name varchar(64) not null unique,
    created_at datetime not null
);

create table suffixes (
    id int primary key auto_increment,
    name varchar(64) not null,
    is_prefix bool not null,
    weight int not null,
    created_at datetime not null
);

insert into words (name, created_at) values ("アンパン", now());
insert into words (name, created_at) values ("ジャム", now());
insert into words (name, created_at) values ("チーズ", now());
insert into words (name, created_at) values ("カレーパン", now());
insert into words (name, created_at) values ("しょくぱん", now());
insert into words (name, created_at) values ("てんどん", now());
insert into words (name, created_at) values ("かつどん", now());
insert into words (name, created_at) values ("かまめし", now());
insert into words (name, created_at) values ("おむすび", now());
insert into words (name, created_at) values ("はみがき", now());
insert into words (name, created_at) values ("はみがきこ", now());
insert into words (name, created_at) values ("ひのたま", now());
insert into words (name, created_at) values ("ミルク", now());
insert into words (name, created_at) values ("やかん", now());
insert into words (name, created_at) values ("おそうじ", now());
insert into words (name, created_at) values ("タワシ", now());
insert into words (name, created_at) values ("バケツ", now());
insert into words (name, created_at) values ("あかちゃん", now());
insert into words (name, created_at) values ("ハンバーガー", now());
insert into words (name, created_at) values ("ありんこ", now());
insert into words (name, created_at) values ("かつぶし", now());
insert into words (name, created_at) values ("ニガウリ", now());
insert into words (name, created_at) values ("やきそばパン", now());
insert into words (name, created_at) values ("ながねぎ", now());
insert into words (name, created_at) values ("こねぎ", now());
insert into words (name, created_at) values ("しらたき", now());
insert into words (name, created_at) values ("しゅんぎく", now());
insert into words (name, created_at) values ("だてまき", now());
insert into words (name, created_at) values ("ラーメン", now());
insert into words (name, created_at) values ("たこやき", now());
insert into words (name, created_at) values ("ポット", now());
insert into words (name, created_at) values ("りんご", now());
insert into words (name, created_at) values ("ドーナツ", now());
insert into words (name, created_at) values ("SL", now());
insert into words (name, created_at) values ("エクレア", now());
insert into words (name, created_at) values ("プリン", now());
insert into words (name, created_at) values ("カステラ", now());
insert into words (name, created_at) values ("ドリアン", now());
insert into words (name, created_at) values ("アボカド", now());
insert into words (name, created_at) values ("おくら", now());
insert into words (name, created_at) values ("ゆず", now());
insert into words (name, created_at) values ("おおかみ", now());
insert into words (name, created_at) values ("しらたま", now());
insert into words (name, created_at) values ("だいこん", now());
insert into words (name, created_at) values ("しろかぶ", now());
insert into words (name, created_at) values ("ゆでたまご", now());
insert into words (name, created_at) values ("さつまあげ", now());
insert into words (name, created_at) values ("つみれ", now());
insert into words (name, created_at) values ("こんぶ", now());
insert into words (name, created_at) values ("ふろふきだいこん", now());
insert into words (name, created_at) values ("ばいきん", now());
insert into words (name, created_at) values ("チョコ", now());
insert into words (name, created_at) values ("ツリー", now());
insert into words (name, created_at) values ("クレヨン", now());
insert into words (name, created_at) values ("どろみず", now());
insert into words (name, created_at) values ("へどろ", now());
insert into words (name, created_at) values ("こおり", now());
insert into words (name, created_at) values ("すな", now());
insert into words (name, created_at) values ("ゆき", now());
insert into words (name, created_at) values ("くらやみ", now());
insert into words (name, created_at) values ("くろバラ", now());
insert into words (name, created_at) values ("どろんこ", now());
insert into words (name, created_at) values ("くろゆき", now());
insert into words (name, created_at) values ("おまわりさん", now());
insert into words (name, created_at) values ("レアチーズ", now());
insert into words (name, created_at) values ("ゆうびんやさん", now());
insert into words (name, created_at) values ("ロバ", now());
insert into words (name, created_at) values ("やぎ", now());
insert into words (name, created_at) values ("くだものやさん", now());
insert into words (name, created_at) values ("うさぎ", now());
insert into words (name, created_at) values ("クマ", now());
insert into words (name, created_at) values ("ブタ", now());
insert into words (name, created_at) values ("ワニ", now());
insert into words (name, created_at) values ("とんかつ", now());
insert into words (name, created_at) values ("しずく", now());
insert into words (name, created_at) values ("マーガレット", now());
insert into words (name, created_at) values ("アルミ", now());
insert into words (name, created_at) values ("ショコラ", now());
insert into words (name, created_at) values ("サラダ", now());
insert into words (name, created_at) values ("クレソン", now());
insert into words (name, created_at) values ("マロン", now());
insert into words (name, created_at) values ("くさもち", now());
insert into words (name, created_at) values ("そうめん", now());
insert into words (name, created_at) values ("てんぷら", now());
insert into words (name, created_at) values ("いしうす", now());
insert into words (name, created_at) values ("けんちん", now());
insert into words (name, created_at) values ("かんぴょう", now());
insert into words (name, created_at) values ("こんにゃく", now());
insert into words (name, created_at) values ("だいふく", now());
insert into words (name, created_at) values ("いちごだいふく", now());
insert into words (name, created_at) values ("にんにく", now());
insert into words (name, created_at) values ("ふくろう", now());
insert into words (name, created_at) values ("どんぐり", now());
insert into words (name, created_at) values ("バック", now());
insert into words (name, created_at) values ("かさ", now());
insert into words (name, created_at) values ("はちみつ", now());
insert into words (name, created_at) values ("つくし", now());
insert into words (name, created_at) values ("ミノムシ", now());
insert into words (name, created_at) values ("シチュー", now());
insert into words (name, created_at) values ("あんず", now());
insert into words (name, created_at) values ("クルミ", now());
insert into words (name, created_at) values ("すずらん", now());
insert into words (name, created_at) values ("チェロ", now());
insert into words (name, created_at) values ("もっきん", now());
insert into words (name, created_at) values ("ドクダミ", now());
insert into words (name, created_at) values ("ふきのとう", now());
insert into words (name, created_at) values ("カスタネット", now());
insert into words (name, created_at) values ("ぎんなん", now());
insert into words (name, created_at) values ("シナモンロール", now());
insert into words (name, created_at) values ("ホットケーキ", now());
insert into words (name, created_at) values ("シロップ", now());
insert into words (name, created_at) values ("たけトンボ", now());
insert into words (name, created_at) values ("たけのこ", now());
insert into words (name, created_at) values ("おこと", now());
insert into words (name, created_at) values ("やつはし", now());
insert into words (name, created_at) values ("つばき", now());
insert into words (name, created_at) values ("かしわもち", now());
insert into words (name, created_at) values ("さくらもち", now());
insert into words (name, created_at) values ("たぬき", now());
insert into words (name, created_at) values ("おんせん", now());
insert into words (name, created_at) values ("しかく", now());
insert into words (name, created_at) values ("しぶがき", now());
insert into words (name, created_at) values ("ケーキ", now());
insert into words (name, created_at) values ("さんかく", now());
insert into words (name, created_at) values ("さび", now());
insert into words (name, created_at) values ("ほしがき", now());
insert into words (name, created_at) values ("こいのぼり", now());
insert into words (name, created_at) values ("ほおずき", now());
insert into words (name, created_at) values ("ゆげ", now());
insert into words (name, created_at) values ("もくば", now());
insert into words (name, created_at) values ("トースター", now());
insert into words (name, created_at) values ("たくわん", now());
insert into words (name, created_at) values ("ウーロン", now());
insert into words (name, created_at) values ("ドライヤー", now());
insert into words (name, created_at) values ("おしんこ", now());
insert into words (name, created_at) values ("ざくろ", now());
insert into words (name, created_at) values ("チーズフォンデュ", now());
insert into words (name, created_at) values ("わらび", now());
insert into words (name, created_at) values ("ぜんまい", now());
insert into words (name, created_at) values ("かるいし", now());
insert into words (name, created_at) values ("おしるこ", now());
insert into words (name, created_at) values ("かまあげうどん", now());
insert into words (name, created_at) values ("トナカイ", now());
insert into words (name, created_at) values ("コンドル", now());
insert into words (name, created_at) values ("けしゴム", now());
insert into words (name, created_at) values ("えんぴつ", now());
insert into words (name, created_at) values ("ノート", now());
insert into words (name, created_at) values ("スケール", now());
insert into words (name, created_at) values ("ランプ", now());
insert into words (name, created_at) values ("はんごう", now());
insert into words (name, created_at) values ("バオバブ", now());
insert into words (name, created_at) values ("ポテト", now());
insert into words (name, created_at) values ("コロッケ", now());
insert into words (name, created_at) values ("サボテン", now());
insert into words (name, created_at) values ("ほうれんそう", now());
insert into words (name, created_at) values ("とうだい", now());
insert into words (name, created_at) values ("やきいも", now());
insert into words (name, created_at) values ("まめ", now());
insert into words (name, created_at) values ("そらまめ", now());
insert into words (name, created_at) values ("ブルーベリー", now());
insert into words (name, created_at) values ("ジャガイモ", now());
insert into words (name, created_at) values ("たまご", now());
insert into words (name, created_at) values ("おんどり", now());
insert into words (name, created_at) values ("めんどり", now());
insert into words (name, created_at) values ("くまで", now());
insert into words (name, created_at) values ("じょうろ", now());
insert into words (name, created_at) values ("スコップ", now());
insert into words (name, created_at) values ("うきわ", now());
insert into words (name, created_at) values ("はまぐり", now());
insert into words (name, created_at) values ("ホットサンド", now());
insert into words (name, created_at) values ("しろくま", now());
insert into words (name, created_at) values ("あくび", now());
insert into words (name, created_at) values ("バナナ", now());
insert into words (name, created_at) values ("ババロア", now());
insert into words (name, created_at) values ("ホラー", now());
insert into words (name, created_at) values ("うどん", now());
insert into words (name, created_at) values ("てんぷらそば", now());
insert into words (name, created_at) values ("コチョウラン", now());
insert into words (name, created_at) values ("ぶたまん", now());
insert into words (name, created_at) values ("マリネ", now());
insert into words (name, created_at) values ("ナン", now());
insert into words (name, created_at) values ("しろバラ", now());
insert into words (name, created_at) values ("バター", now());
insert into words (name, created_at) values ("カレー", now());
insert into words (name, created_at) values ("メロン", now());
insert into words (name, created_at) values ("クリーム", now());
insert into words (name, created_at) values ("おにぎり", now());
insert into words (name, created_at) values ("てっかまき", now());
insert into words (name, created_at) values ("にんじゃ", now());
insert into words (name, created_at) values ("やきそば", now());
insert into words (name, created_at) values ("ソース", now());
insert into words (name, created_at) values ("ネギ", now());
insert into words (name, created_at) values ("くも", now());
insert into words (name, created_at) values ("あまぐも", now());
insert into words (name, created_at) values ("おばけ", now());
insert into words (name, created_at) values ("だるま", now());
insert into words (name, created_at) values ("のり", now());
insert into words (name, created_at) values ("ゆうれい", now());
insert into words (name, created_at) values ("くしゃみ", now());
insert into words (name, created_at) values ("ビーだま", now());
insert into words (name, created_at) values ("ゴリラ", now());
insert into words (name, created_at) values ("クリスマス", now());
insert into words (name, created_at) values ("にじ", now());
insert into words (name, created_at) values ("ことり", now());
insert into words (name, created_at) values ("けむし", now());
insert into words (name, created_at) values ("あめ", now());
insert into words (name, created_at) values ("アメ", now());
insert into words (name, created_at) values ("くり", now());
insert into words (name, created_at) values ("くりきんとん", now());
insert into words (name, created_at) values ("だんご", now());
insert into words (name, created_at) values ("ラクダ", now());
insert into words (name, created_at) values ("ミイラ", now());
insert into words (name, created_at) values ("スフィンクス", now());
insert into words (name, created_at) values ("ケチャップ", now());
insert into words (name, created_at) values ("ソテー", now());
insert into words (name, created_at) values ("かぼちゃ", now());
insert into words (name, created_at) values ("たまねぎ", now());
insert into words (name, created_at) values ("オニオン", now());
insert into words (name, created_at) values ("ロコモコ", now());
insert into words (name, created_at) values ("ゴムまり", now());
insert into words (name, created_at) values ("スタンプ", now());
insert into words (name, created_at) values ("ダンボール", now());
insert into words (name, created_at) values ("オルゴール", now());
insert into words (name, created_at) values ("てっこつ", now());
insert into words (name, created_at) values ("ピエロ", now());
insert into words (name, created_at) values ("サンタ", now());
insert into words (name, created_at) values ("ねこ", now());
insert into words (name, created_at) values ("いぬ", now());
insert into words (name, created_at) values ("フラワー", now());
insert into words (name, created_at) values ("キリン", now());
insert into words (name, created_at) values ("ゾウ", now());
insert into words (name, created_at) values ("ペンギン", now());
insert into words (name, created_at) values ("コウモリ", now());
insert into words (name, created_at) values ("わんこそば", now());
insert into words (name, created_at) values ("こうてつ", now());
insert into words (name, created_at) values ("きつね", now());
insert into words (name, created_at) values ("フライパン", now());
insert into words (name, created_at) values ("なだれ", now());
insert into words (name, created_at) values ("マンモス", now());
insert into words (name, created_at) values ("タイヤ", now());
insert into words (name, created_at) values ("ダイヤ", now());
insert into words (name, created_at) values ("たんこぶ", now());
insert into words (name, created_at) values ("みずばしょう", now());
insert into words (name, created_at) values ("ひつじ", now());
insert into words (name, created_at) values ("アライグマ", now());
insert into words (name, created_at) values ("カバ", now());
insert into words (name, created_at) values ("カエル", now());
insert into words (name, created_at) values ("みかん", now());
insert into words (name, created_at) values ("スイカ", now());
insert into words (name, created_at) values ("ぶどう", now());
insert into words (name, created_at) values ("グレープフルーツ", now());
insert into words (name, created_at) values ("にくまん", now());
insert into words (name, created_at) values ("ピザ", now());
insert into words (name, created_at) values ("ピザまん", now());
insert into words (name, created_at) values ("ラ・フランス", now());
insert into words (name, created_at) values ("たいやき", now());
insert into words (name, created_at) values ("サンマ", now());
insert into words (name, created_at) values ("アジフライ", now());
insert into words (name, created_at) values ("ウナギ", now());
insert into words (name, created_at) values ("ウーパールーパー", now());
insert into words (name, created_at) values ("チンアナゴ", now());
insert into words (name, created_at) values ("アナゴ", now());
insert into words (name, created_at) values ("ワカメ", now());
insert into words (name, created_at) values ("サザエ", now());
insert into words (name, created_at) values ("カツオ", now());
insert into words (name, created_at) values ("タラ", now());
insert into words (name, created_at) values ("ブーメラン", now());
insert into words (name, created_at) values ("マグロ", now());
insert into words (name, created_at) values ("イクラ", now());
insert into words (name, created_at) values ("かずのこ", now());
insert into words (name, created_at) values ("ソーセージ", now());
insert into words (name, created_at) values ("ウインナー", now());
insert into words (name, created_at) values ("ハム", now());
insert into words (name, created_at) values ("ベーコン", now());
insert into words (name, created_at) values ("レタス", now());
insert into words (name, created_at) values ("キャベツ", now());
insert into words (name, created_at) values ("ナス", now());
insert into words (name, created_at) values ("サニーレタス", now());
insert into words (name, created_at) values ("むらさきキャベツ", now());
insert into words (name, created_at) values ("ピーマン", now());
insert into words (name, created_at) values ("パプリカ", now());
insert into words (name, created_at) values ("ごぼう", now());
insert into words (name, created_at) values ("トマト", now());
insert into words (name, created_at) values ("イカ", now());
insert into words (name, created_at) values ("ポテトチップス", now());
insert into words (name, created_at) values ("コンパス", now());
insert into words (name, created_at) values ("DVD", now());
insert into words (name, created_at) values ("ブルーレイ", now());
insert into words (name, created_at) values ("カセット", now());
insert into words (name, created_at) values ("コップ", now());
insert into words (name, created_at) values ("メガネ", now());
insert into words (name, created_at) values ("ギター", now());
insert into words (name, created_at) values ("ドラム", now());
insert into words (name, created_at) values ("ピアノ", now());
insert into words (name, created_at) values ("ベース", now());
insert into words (name, created_at) values ("トランペット", now());
insert into words (name, created_at) values ("タンバリン", now());
insert into words (name, created_at) values ("コントラバス", now());
insert into words (name, created_at) values ("ハープ", now());

insert into suffixes (name, is_prefix, weight, created_at) values ("いぬの", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おうじ", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おうじょ", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おくさん", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おじいさん", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おじさん", false, 10, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おしょう", false, 5, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おとこ", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おに", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おばけ", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("おばさん", false, 5, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("かあさん", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("かいじゅう", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("がはく", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("キッド", false, 3, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("くん", false, 18, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("けんし", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("こぞう", false, 3, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ゴリラ", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("コング", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ざちょう", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("さん", false, 13, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("じいさん", false, 4, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("じいや", false, 3, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("しちょう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("じょおう", false, 3, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("せんせい", false, 4, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("せんにん", false, 3, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("そんちょう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("だいおう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("だいまおう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("たろう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("だんしゃく", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("チーフ", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ちび", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("チビ", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ちゃん", false, 22, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("てんし", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ドクター・", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("どん", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("にんじゃの", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ねえさん", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("のじょおう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("のへいし", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("のまおう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("はくしゃく", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ひめ", false, 9, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ふじん", false, 2, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ブラザーズ", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ベビー", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ほあんかん", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ぼうや", false, 7, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("まおう", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("マダム", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("マダム・", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("まほうの", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("まぼろしの", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("マン", false, 17, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("まん", false, 17, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ミス・", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("めいけん", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("モンスター", false, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("やぎの", true, 1, now());
insert into suffixes (name, is_prefix, weight, created_at) values ("ようせい", true, 1, now());
